const $=id=>document.getElementById(id);
let lastGeneratedMs=0;
const num=n=>new Intl.NumberFormat().format(Number(n||0));
const pct=v=>v===null||v===undefined?'PENDING':`${Number(v).toFixed(2)}%`;
const fmt=v=>v===null||v===undefined||v===''?'--':String(v);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pretty=s=>String(s??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const localTime=s=>s?new Date(s).toLocaleString():'--';
function setText(id,v){const el=$(id);if(el)el.textContent=v}
function tone(v){const s=String(v||'').toUpperCase();if(['GREEN','PASS','ACTIVE','OK','WIN','RUNNING','FULL'].some(x=>s.includes(x)))return'green';if(['AMBER','WAIT','CANARY','WARM'].some(x=>s.includes(x)))return'amber';if(['RED','FAIL','ERROR','LOSS','DEMOTED','STALE'].some(x=>s.includes(x)))return'red';return'neutral'}
function badge(v){return `<span class="badge ${tone(v)}">${esc(pretty(v||'UNKNOWN'))}</span>`}
function detail(label,value,small=''){return `<div class="detail-item"><span>${esc(label)}</span><strong>${esc(fmt(value))}</strong>${small?`<small>${esc(small)}</small>`:''}</div>`}
function empty(text){return `<div class="empty-state">${esc(text)}</div>`}
function ruleChips(rule){return `<div class="rule-line">${(rule||[]).map(x=>`<span class="rule-chip">${esc(pretty(x.field))}: ${esc(fmt(x.value))}</span>`).join('')}</div>`}
function barChart(id,rows,labelFn,valueFn,maxValue=null){const vals=rows.map(valueFn).map(v=>Number(v)||0),max=maxValue||Math.max(1,...vals),el=$(id);if(!el)return;el.innerHTML=rows.length?rows.map((r,i)=>`<div class="chart-row"><span>${esc(labelFn(r))}</span><div class="chart-track"><i style="width:${Math.min(100,Math.max(0,vals[i]/max*100))}%"></i></div><strong>${esc(vals[i].toFixed(2))}</strong></div>`).join(''):empty('No chart data yet')}
function renderLive(l){setText('stripBot',l.running?'RUNNING':'STOPPED');setText('stripDecision',l.decision||'--');setText('liveBadge',l.demo_only?'DEMO ONLY':'CHECK MODE');const book=l.order_book||{},flow=l.futures_flow||{},oi=l.open_interest||{},ctx=l.ten_minute_context||{};$('liveGrid').innerHTML=[detail('Decision',l.decision,l.reason),detail('Side / path',`${fmt(l.side)} / ${fmt(l.path)}`),detail('Trigger',`${fmt(l.trigger)} / ${fmt(l.trigger_kind)}`),detail('5m phase',l.five_minute_phase),detail('Quote age',`${Number(l.quote_age_ms||0).toFixed(0)} ms`),detail('Spread',Number(l.spread||0).toFixed(2)),detail('Order book',book.ready&&!book.stale?'READY':'NOT READY',`pressure ${fmt(book.pressure_now)}`),detail('Futures flow',flow.ready&&!flow.stale?'READY':'NOT READY',`1m ${fmt(flow.flow_1m)} / 5m ${fmt(flow.flow_5m)}`),detail('Open interest',oi.ready&&!oi.stale?'READY':'NOT READY',`change ${fmt(oi.change_pct)}%`),detail('10m demand',ctx.demand?`${ctx.demand.low}–${ctx.demand.high}`:'NONE',ctx.demand?.state||''),detail('10m supply',ctx.supply?`${ctx.supply.low}–${ctx.supply.high}`:'NONE',ctx.supply?.state||'')].join('')}
function renderResearch(r){setText('stripResearch',r.overall||'UNKNOWN');setText('stripPhase',pretty(r.research_phase||'--'));setText('researchBadge',r.model_degraded?'DEGRADED':'PREFERRED MODEL');$('researchGrid').innerHTML=[detail('Frontier model',r.model,r.model_state),detail('GPU endpoint',r.gpu_endpoint),detail('Supervisor',r.supervisor_status,r.research_phase),detail('Last deep search',localTime(r.last_deep_search_utc)),detail('Last directed family',r.last_directed_family,r.last_directed_outcome),detail('Collector age',r.collector_age_seconds===null?'UNKNOWN':`${Math.round(r.collector_age_seconds||0)}s`),detail('MT5 sync age',r.mt5_sync_age_seconds===null?'UNKNOWN':`${Math.round(r.mt5_sync_age_seconds||0)}s`),detail('Watchdog age',r.watchdog_age_seconds===null?'UNKNOWN':`${Math.round(r.watchdog_age_seconds||0)}s`),detail('Runs',`${r.directed_runs||0} directed / ${r.hourly_runs||0} hourly`),detail('Promotions learned',`${r.canary_promotions||0} canary / ${r.full_promotions||0} full`)].join('')}
function renderSignals(s){const rows=s.candidates||[];setText('stripCandidates',rows.filter(x=>['CANARY','FULL'].includes(x.eligibility)).length);setText('signalUpdated',localTime(s.updated_utc));barChart('signalChart',rows.slice(0,8),x=>x.family,x=>Math.min(Number(x.long_term?.profit_factor_r||0),10),10);$('signalTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Family</th><th>Tier</th><th>Samples</th><th>PF</th><th>Exp R</th><th>/hr</th><th>/day</th><th>Rule</th></tr></thead><tbody>${rows.map(x=>`<tr><td data-label="Family">${esc(x.family)}</td><td data-label="Tier">${badge(x.eligibility)}</td><td data-label="Samples">${esc(x.matched_resolved)}</td><td data-label="PF">${esc(fmt(x.long_term?.profit_factor_r))}</td><td data-label="Exp R">${esc(fmt(x.long_term?.expectancy_r))}</td><td data-label="Per hour">${Number(x.opportunities_per_hour||0).toFixed(2)}</td><td data-label="Per day">${Number(x.opportunities_per_day||0).toFixed(1)}</td><td data-label="Rule">${ruleChips(x.rule)}</td></tr>`).join('')}</tbody></table>`:empty('No signal candidates published yet')}
function renderPromotions(rows){const active=rows.filter(x=>x.status==='ACTIVE').length;setText('stripPromotions',`${active} active / ${rows.length} tracked`);barChart('promotionChart',[{name:'FULL',n:rows.filter(x=>x.tier==='FULL').length},{name:'DEMO CANARY',n:rows.filter(x=>x.tier==='DEMO_CANARY').length}],x=>x.name,x=>x.n);$('promotionList').innerHTML=rows.length?rows.map(x=>`<article class="info-card"><h3>${esc(x.family)}</h3><p>${badge(x.tier)} ${badge(x.status)}</p><p>Proposal ${esc(x.proposal_id)} · verifier ${esc(x.verifier_decision)} / ${esc(x.verifier_status)}</p><p>PF ${esc(fmt(x.profit_factor_r))} · expectancy ${esc(fmt(x.expectancy_r))}R · ${esc(fmt(x.opportunities_per_hour))}/hr</p><p>Health: ${esc(pretty(x.health_decision||'unknown'))}${x.demotion_reasons?.length?` · ${esc(x.demotion_reasons.join(', '))}`:''}</p>${ruleChips(x.rule)}</article>`).join(''):empty('No promotions recorded')}
function renderHistory(h){const rows=h.verifier||[],counts={PASS:0,CANARY_PASS:0,FAIL:0};rows.forEach(x=>{if(x.decision==='PASS')counts.PASS++;else if(x.decision==='CANARY_PASS')counts.CANARY_PASS++;else if(x.decision==='FAIL')counts.FAIL++});barChart('historyChart',Object.entries(counts).map(([name,n])=>({name,n})),x=>x.name,x=>x.n);$('historyList').innerHTML=rows.length?rows.slice(0,15).map(x=>`<article class="info-card"><h3>Proposal ${esc(x.proposal_id??'--')} · ${esc(x.family||pretty(x.stage))}</h3><p>${badge(x.decision)} · ${esc(localTime(x.utc))}</p>${x.reasons?.length?`<p>${esc(x.reasons.join(' · '))}</p>`:'<p>No verifier rejection reasons.</p>'}</article>`).join(''):empty('No verifier history available')}
function renderTrading(t){const s=t.summary||{},rows=t.recent||[];setText('tradingSummary',`${s.wins||0}W / ${s.losses||0}L · ${fmt(s.win_rate)}% · net ${fmt(s.net_profit)}`);barChart('tradingChart',[{name:'Wins',n:s.wins||0},{name:'Losses',n:s.losses||0}],x=>x.name,x=>x.n);$('tradingList').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Exit</th><th>Side</th><th>Family</th><th>Result</th><th>Profit</th></tr></thead><tbody>${rows.slice(0,20).map(x=>`<tr><td data-label="Exit">${esc(localTime(x.exit_utc))}</td><td data-label="Side">${esc(x.side)}</td><td data-label="Family">${esc(x.family||'UNKNOWN')}</td><td data-label="Result">${badge(x.result)}</td><td data-label="Profit">${esc(fmt(x.profit))}</td></tr>`).join('')}</tbody></table>`:empty('No completed demo trades yet')}
function renderHealth(rows){$('healthGrid').innerHTML=rows.length?rows.map(x=>`<article class="health-item ${esc(String(x.state||'').toLowerCase())}"><span>${esc(x.name)}</span><strong>${esc(x.state)}</strong><small>${x.age_seconds===null||x.age_seconds===undefined?'semantic check':`${Number(x.age_seconds).toFixed(1)}s old`} · ${esc(x.detail||'')}</small></article>`).join(''):empty('No health data available');const worst=rows.some(x=>x.state==='RED')?'RED':rows.some(x=>x.state==='AMBER')?'AMBER':'GREEN';setText('healthLabel',worst==='GREEN'?'SYSTEM HEALTHY':worst==='AMBER'?'SYSTEM WARNING':'SYSTEM ATTENTION');const dot=$('healthDot');if(dot)dot.className=`health-dot ${worst.toLowerCase()}`}
function metricClass(el,v,target=98){if(!el)return;el.classList.remove('good','warn','bad');if(v===null||v===undefined)return;if(v>=target)el.classList.add('good');else if(v>=80)el.classList.add('warn');else el.classList.add('bad')}
function renderStage(s){const icon=s.state==='complete'?'✓':s.state==='working'?'↻':'•',sp=Number(s.percent??((s.fraction||0)*100));const subs=Object.entries(s.subchecklist||{}).map(([k,v])=>`<div class="subcheck-row"><span>${esc(pretty(k))}</span><strong>${Number(v).toFixed(2)}%</strong></div>`).join('');return `<article class="stage ${esc(s.state)}"><div class="stage-icon">${icon}</div><div><h3>${esc(s.name)}</h3><div class="stage-progress stage-percent"><div><i style="width:${Math.max(0,Math.min(100,sp))}%"></i></div><strong>${sp.toFixed(2)}%</strong></div><p>${esc(s.detail)}</p>${s.finding?`<p class="finding">${esc(s.finding)}</p>`:''}${subs?`<div class="subchecklist">${subs}</div>`:''}</div><div class="state">${esc(s.state)}</div></article>`}
function renderLegacy(d){const h=d.system||{};setText('activeStage',h.active_stage||'No active stage');const p=d.progress||{};setText('overallPct',`${Number(p.overall||0).toFixed(1)}%`);const ob=$('overallBar');if(ob)ob.style.width=`${Math.max(0,Math.min(100,p.overall||0))}%`;setText('dataPct',`${Number(p.data_build||0).toFixed(1)}%`);setText('validationPct',`${Number(p.validation||0).toFixed(1)}%`);setText('updatedAt',localTime(d.generated_utc));const m=d.metrics||{};setText('mt5Wr',pct(m.mt5_win_rate));setText('mt5Label',m.mt5_label||'--');metricClass($('mt5Wr'),m.mt5_win_rate);setText('binanceWr',pct(m.binance_win_rate));setText('binanceLabel',m.binance_label||'--');metricClass($('binanceWr'),m.binance_win_rate);setText('combinedWr',pct(m.combined_win_rate));setText('combinedLabel',m.combined_label||'--');metricClass($('combinedWr'),m.combined_win_rate);setText('tradesDay',Number(m.qualifying_trades_per_day||0).toFixed(2));setText('tradeTarget',`Legacy research target: ${m.trade_target_per_day||100}/day at ${m.target_win_rate||98}% WR`);const q=d.structure||{};setText('structureStage',pretty(q.structure_stage||'pending'));setText('structureProgress',`${Number(q.structure_progress||0).toFixed(2)}%`);setText('structureDays',`${q.structure_days||0}/${q.structure_days_total||183}`);setText('structureTicks',num(q.structure_ticks));setText('structureEvents',num(q.structure_events));setText('structureSuccess',`${num(q.structure_success_rows)} / ${num(q.structure_success_target)}`);setText('structureCoverage',`${Number(q.structure_coverage||0).toFixed(2)}%`);setText('structureHealth',q.structure_health||'WAITING');setText('structureError',`${q.structure_health||'WAITING'} / ${num(q.structure_error_bytes||0)} B`);const sb=d.structural_broker||{};setText('structBrokerStage',pretty(sb.stage||'pending'));setText('structBrokerProgress',`${Number(sb.progress||0).toFixed(2)}%`);setText('structBrokerCandidates',num(sb.raw_dollar95_candidates));setText('structBrokerGeometries',num(sb.primary_geometries||36));setText('structBrokerRaw95',num(sb.raw_broker95_combos));setText('structBrokerExact95',num(sb.exact95_structural_valid));setText('structBrokerPre98',num(sb.exact98_pretiming));setText('structBrokerHealth',sb.health||'WAITING');setText('structBrokerError',`${sb.health||'WAITING'} / ${num(sb.error_bytes||0)} B`);const c=d.counts||{};setText('tickCount',num(c.mt5_ticks));setText('stateDays',`${c.state_days_complete||0}/${c.state_days_total||365}`);setText('featureCount',num(c.mt5_features));setText('ruleCount',num(c.prior_exact_bin_rules));const stages=d.stages||[];setText('stageCount',`${stages.filter(s=>s.state==='complete').length}/${stages.length} complete`);const sl=$('stageList');if(sl)sl.innerHTML=stages.map(renderStage).join('');const notes=$('notes');if(notes)notes.innerHTML=(d.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}
function render(d){if(Number(d.schema_version)!==2)throw new Error('Unsupported schema_version');const when=d.generated_utc?new Date(d.generated_utc):null;lastGeneratedMs=when?when.getTime():0;renderLive(d.live||{});renderResearch(d.research||{});renderSignals(d.signals||{});renderPromotions(d.promotions||[]);renderHistory(d.history||{});renderTrading(d.trading||{});renderHealth(d.health||[]);renderLegacy(d);staleCheck()}
async function refresh(){try{const r=await fetch(`https://raw.githubusercontent.com/theliquidationlab/liquidity-labs-research/main/data/status.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json())}catch(e){setText('healthLabel','DATA OFFLINE');setText('activeStage','Dashboard could not load schema-v2 status');const dot=$('healthDot');if(dot)dot.className='health-dot red'}}
function staleCheck(){const stale=Boolean(lastGeneratedMs&&Date.now()-lastGeneratedMs>20*60*1000),banner=$('staleBanner');if(banner)banner.hidden=!stale;if(stale){setText('healthLabel','STATUS STALE');setText('activeStage','Published VPS data is more than 20 minutes old');const dot=$('healthDot');if(dot)dot.className='health-dot red'}}
refresh();setInterval(refresh,60000);setInterval(staleCheck,30000);
